# Generated by Django 4.1.5 on 2023-01-16 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='photography',
            options={'verbose_name': 'Fotografia', 'verbose_name_plural': 'Fotografias'},
        ),
        migrations.AddField(
            model_name='photography',
            name='category',
            field=models.CharField(choices=[(1, 'Nebulosa'), (2, 'Estrela'), (3, 'Galáxia'), (4, 'Planeta')], default='', max_length=100),
        ),
    ]
