# Generated by Django 4.1.5 on 2023-01-20 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0002_alter_photography_options_photography_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='photography',
            name='is_published',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='photography',
            name='category',
            field=models.CharField(choices=[('1', 'Nebulosa'), ('2', 'Estrela'), ('3', 'Galáxia'), ('4', 'Planeta')], default='', max_length=100),
        ),
    ]
