# Generated by Django 4.1.5 on 2023-01-20 00:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0003_photography_is_published_alter_photography_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='photography',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
