# Generated by Django 4.1.5 on 2023-01-20 00:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0004_photography_created_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='photography',
            old_name='created_at',
            new_name='date',
        ),
    ]
